### ISSUE TITLE
Option+F1 is not recognised properly in IntelliJ

### ISSUE THREAD

**Issue by Fizol** [donniebreve/touchcursor-mac#9]
Hi,

I've been using Option+F1 shortcut in IntelliJ and after running touchcursor it's not working like it should.

any tips how to debug it? where to find it in code?

Regards

**Comment by donniebreve** [comment]
This is the relevant part of the code that would apply the option modifier.

https://github.com/donniebreve/touchcursor-mac/blob/22e1ea903083490983e68aa6da828ab973d399db/src/cgEventVirtualKeyboard.mm#L422

**Comment by donniebreve** [comment]
Hey @Fizol, I think there's definitely something weird with the function keys. I've noticed if you enable the Keyboard setting `Use F1, F2, etc. keys as standard function keys`, then things seem to work as intended.

It seems like if that setting is disabled, then when we send a F key through the application, MacOS for some reason believes the Fn key has been pressed, or is somehow a modifier. I wonder if you set your IntelliJ shortcut to opt+fn+f1, it might work with the setting disabled.

Dealing with this keyboard setting is something I figured I would have to handle eventually... now possibly sooner rather than later.

**Comment by donniebreve** [comment]
@Fizol I've racked my brain over this for a while, but I just can't reproduce it. I've tested in a few different applications, specifically in VSCodium (the default alt+f1 keybind is an accessibility window that pops up), and the alt+f1 combination seems to be functioning. Feel free to reopen if you have more information.
